services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app   
    environment:
      - NODE_ENV=development
    command: npm run dev
