services:
  backend:
    build:
      context: ./backend
      target: production
    container_name: backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    command: npm start
