export const productsData = {
  data: [
    {
      id: 1,
      name: "Wireless Noise-Cancelling Headphones",
      description:
        "High-quality over-ear wireless headphones with active noise cancellation and 30-hour battery life.",
      quantity: 25,
      price: 100,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173110/products/zjvri21cmvzdpc9ppf3u.webp",
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173109/products/oywfbfmwkfbficdxmnlf.png",
      ],
      createdAt: "2025-11-03T12:31:51.288Z",
      categoryId: 1,
      categories: {
        id: 1,
        name: "Electronics",
        description: "Electronic devices",
        thumbnail: "thumbnail",
      },
    },
    {
      id: 2,
      name: "Gaming Mouse",
      description: "High precision RGB gaming mouse with programmable buttons.",
      quantity: 15,
      price: 50,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:32:00.288Z",
      categoryId: 2,
      categories: {
        id: 2,
        name: "Gaming",
        description: "Gaming peripherals",
        thumbnail: "thumbnail",
      },
    },
    {
      id: 3,
      name: "Mechanical Keyboard",
      description: "Durable mechanical keyboard with RGB backlight.",
      quantity: 10,
      price: 120,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:32:10.288Z",
      categoryId: 2,
      categories: {
        id: 2,
        name: "Gaming",
        description: "Gaming peripherals",
        thumbnail: "thumbnail",
      },
    },
    {
      id: 4,
      name: "Wireless Charger",
      description: "Fast wireless charging pad for smartphones.",
      quantity: 5,
      price: 30,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:32:20.288Z",
      categoryId: 1,
      categories: {
        id: 1,
        name: "Electronics",
        description: "Electronic devices",
        thumbnail: "thumbnail",
      },
    },
    {
      id: 5,
      name: "Bluetooth Speaker",
      description: "Portable Bluetooth speaker with 12-hour battery life.",
      quantity: 20,
      price: 70,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:32:30.288Z",
      categoryId: 1,
      categories: { id: 1, name: "Electronics", description: "Electronic devices", thumbnail: "thumbnail" },
    },
    {
      id: 6,
      name: "Gaming Headset",
      description: "Surround sound gaming headset with mic.",
      quantity: 12,
      price: 80,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:32:40.288Z",
      categoryId: 2,
      categories: { id: 2, name: "Gaming", description: "Gaming peripherals", thumbnail: "thumbnail" },
    },
    {
      id: 7,
      name: "Smartwatch",
      description: "Fitness smartwatch with heart rate monitor.",
      quantity: 18,
      price: 150,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:32:50.288Z",
      categoryId: 1,
      categories: { id: 1, name: "Electronics", description: "Electronic devices", thumbnail: "thumbnail" },
    },
    {
      id: 8,
      name: "VR Headset",
      description: "Immersive VR headset with adjustable lenses.",
      quantity: 8,
      price: 300,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:33:00.288Z",
      categoryId: 2,
      categories: { id: 2, name: "Gaming", description: "Gaming peripherals", thumbnail: "thumbnail" },
    },
    {
      id: 9,
      name: "Laptop Stand",
      description: "Ergonomic laptop stand for better posture.",
      quantity: 30,
      price: 40,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:33:10.288Z",
      categoryId: 1,
      categories: { id: 1, name: "Electronics", description: "Electronic devices", thumbnail: "thumbnail" },
    },
    {
      id: 10,
      name: "Mechanical Gaming Keyboard",
      description: "RGB mechanical keyboard for gamers.",
      quantity: 14,
      price: 130,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:33:20.288Z",
      categoryId: 2,
      categories: { id: 2, name: "Gaming", description: "Gaming peripherals", thumbnail: "thumbnail" },
    },
    {
      id: 11,
      name: "External Hard Drive",
      description: "1TB portable external hard drive.",
      quantity: 22,
      price: 90,
      thumbnail:
        "https://res.cloudinary.com/dhdlno07z/image/upload/v1762173108/products/kufwnzgkijsgic7xh1km.webp",
      images: [],
      createdAt: "2025-11-03T12:33:30.288Z",
      categoryId: 1,
      categories: { id: 1, name: "Electronics", description: "Electronic devices", thumbnail: "thumbnail" },
    },
  ],
  pagination: {
    total: 11,
    page: 1,
    limit: 10, 
    totalPages: 2,
  },
}